### ISSUE TITLE
ColorPicker throws runtime exception

### ISSUE THREAD

**Issue by runiter** [JFXtras/jfxtras-styles#149]
ColorPicker throws exception when "Custom Color..." link is clicked.
I also looks incorrect:

With setAutomaticallyColorPanes(false):
![image](https://user-images.githubusercontent.com/3038088/77974590-8e50b880-72c5-11ea-8a53-a357f7bb6da1.png)

With setAutomaticallyColorPanes(true):
![image](https://user-images.githubusercontent.com/3038088/77974604-a4f70f80-72c5-11ea-8628-6c8cd0ea9583.png)

Here is small code:

```
Scene scene = new Scene(new Pane(new ColorPicker()), 800, 600);
stage.setScene(scene);
JMetro jMetro = new JMetro(scene, Style.DARK);
// jMetro.setAutomaticallyColorPanes(true);
stage.show();
```

Here is the exception:

```
Mar 30, 2020 8:32:39 PM javafx.scene.control.Control loadSkinClass
SEVERE: Failed to load skin 'impl.jfxtras.styles.jmetro.TextFieldSkin' for control WebColorField@1e8fd65[styleClass=webcolor-field web-field text-input text-field]
java.lang.IllegalArgumentException: argument type mismatch
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at javafx.scene.control.Control.loadSkinClass(Control.java:735)
	at javafx.scene.control.Control$4.invalidated(Control.java:661)
	at javafx.beans.property.StringPropertyBase.markInvalid(StringPropertyBase.java:109)
	at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:144)
	at javafx.css.StyleableStringProperty.set(StyleableStringProperty.java:83)
	at javafx.scene.control.Control$4.set(Control.java:653)
	at javafx.css.StyleableStringProperty.applyStyle(StyleableStringProperty.java:69)
	at javafx.css.StyleableStringProperty.applyStyle(StyleableStringProperty.java:45)
	at javafx.scene.CssStyleHelper.transitionToState(CssStyleHelper.java:774)
	at javafx.scene.Node.impl_processCSS(Node.java:9189)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1249)
	at javafx.scene.control.Control.impl_processCSS(Control.java:868)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Node.processCSS(Node.java:9056)
	at javafx.scene.Scene.doCSSPass(Scene.java:545)
	at javafx.scene.Scene.preferredSize(Scene.java:1643)
	at javafx.scene.Scene.impl_preferredSize(Scene.java:1720)
	at javafx.stage.Window$9.invalidated(Window.java:864)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at javafx.stage.Window.setShowing(Window.java:940)
	at javafx.stage.Window.show(Window.java:955)
	at javafx.stage.Stage.show(Stage.java:259)
	at com.sun.javafx.scene.control.skin.CustomColorDialog.show(CustomColorDialog.java:198)
	at com.sun.javafx.scene.control.skin.ColorPalette$1.handle(ColorPalette.java:127)
	at com.sun.javafx.scene.control.skin.ColorPalette$1.handle(ColorPalette.java:105)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Node.fireEvent(Node.java:8411)
	at javafx.scene.control.Hyperlink.fire(Hyperlink.java:153)
	at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:182)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:96)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:89)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:432)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:410)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:186)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by runiter** [comment]
Hi @dukke 
As a temporary workaround to the issue I mentioned above, is there a way to disable jmetro on ColorPicker dialog box?
I would like to use Modena theme for ColorPicker dialog box but JMetro theme for everything else.

**Comment by dukke** [comment]
Hey Saeid @runiter ,

Thanks for the issue reports.

I'll try to fix this issue in the next coming days.
I haven't styled the color picker yet. I'll also try to style the color picker.

Meanwhile if you discover the fix, you're most welcome to file a PR!

Thanks!

**Comment by runiter** [comment]
Hi @dukke 
I appreciate it.
I tried to find a fix but the styling code seems too complicated/unfamiliar to me.
I shall wait for your fix whenever that might be :)

**Comment by dukke** [comment]
Create a separate issue: issue #150 to track adding a new style for the ColorPicker
