### ISSUE TITLE
Issues with DirectoryChooser

### ISSUE THREAD

**Issue by ThomasDaheim** [JFXtras/jfxtras-styles#183]
Hi,

I have a menu with a menuitem that opens the DirectoryChooser dialog. When I click it first time the dialog opens without any issues. But if I click on any menu after closing the dialog I get the below error message.

JMetro: 11.6.14
Java: OpenJDK 14, JavaFX14
OS: Win10

Not sure what to do here?

```
Exception in thread "JavaFX Application Thread" java.lang.ClassCastException: javafx.scene.control.skin.ButtonSkin incompatible with impl.jfxtras.styles.jmetro.FluentButtonSkin
	at impl.jfxtras.styles.jmetro.FluentButtonSkin$1.getStyleableProperty(FluentButtonSkin.java:41)
	at impl.jfxtras.styles.jmetro.FluentButtonSkin$1.getStyleableProperty(FluentButtonSkin.java:31)
	at javafx.graphics/javafx.scene.CssStyleHelper.resetToInitialValues(CssStyleHelper.java:466)
	at javafx.graphics/javafx.scene.CssStyleHelper.createStyleHelper(CssStyleHelper.java:184)
	at javafx.graphics/javafx.scene.Node.reapplyCss(Node.java:9471)
	at javafx.graphics/javafx.scene.Node.reapplyCss(Node.java:9500)
	at javafx.graphics/javafx.scene.Node.reapplyCss(Node.java:9500)
	at javafx.graphics/javafx.scene.Node.reapplyCss(Node.java:9500)
	at javafx.graphics/javafx.scene.Node.reapplyCss(Node.java:9500)
	at javafx.graphics/javafx.scene.Node.reapplyCss(Node.java:9500)
	at javafx.graphics/javafx.scene.Node.reapplyCss(Node.java:9500)
	at javafx.graphics/javafx.scene.Node.doProcessCSS(Node.java:9653)
	at javafx.graphics/javafx.scene.Node$1.doProcessCSS(Node.java:472)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSSImpl(NodeHelper.java:192)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.superProcessCSSImpl(ParentHelper.java:93)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.superProcessCSS(ParentHelper.java:63)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1369)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9544)
	at javafx.graphics/javafx.scene.Scene.doCSSPass(Scene.java:569)
	at javafx.graphics/javafx.scene.Scene.preferredSize(Scene.java:1747)
	at javafx.graphics/javafx.scene.Scene$2.preferredSize(Scene.java:393)
	at javafx.graphics/com.sun.javafx.scene.SceneHelper.preferredSize(SceneHelper.java:66)
	at javafx.graphics/javafx.stage.Window$12.invalidated(Window.java:1086)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
	at javafx.graphics/javafx.stage.Window.setShowing(Window.java:1174)
	at javafx.graphics/javafx.stage.Window.show(Window.java:1189)
	at javafx.graphics/javafx.stage.PopupWindow.showImpl(PopupWindow.java:472)
	at javafx.graphics/javafx.stage.PopupWindow.show(PopupWindow.java:417)
	at javafx.controls/javafx.scene.control.ContextMenu.doShow(ContextMenu.java:323)
	at javafx.controls/javafx.scene.control.ContextMenu.show(ContextMenu.java:265)
	at javafx.controls/javafx.scene.control.skin.MenuButtonSkinBase.show(MenuButtonSkinBase.java:304)
	at javafx.controls/javafx.scene.control.skin.MenuButtonSkinBase.lambda$new$4(MenuButtonSkinBase.java:166)
	at javafx.scene.control.skin.MenuButtonSkinBase$$Lambda$610/0000000000000000.accept(Unknown Source)
	at javafx.controls/com.sun.javafx.scene.control.LambdaMultiplePropertyChangeListenerHandler.lambda$new$1(LambdaMultiplePropertyChangeListenerHandler.java:49)
	at javafx.controls/com.sun.javafx.scene.control.LambdaMultiplePropertyChangeListenerHandler$$Lambda$612/0000000000000000.changed(Unknown Source)
	at javafx.base/javafx.beans.value.WeakChangeListener.changed(WeakChangeListener.java:86)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:360)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.base/javafx.beans.property.ReadOnlyBooleanPropertyBase.fireValueChangedEvent(ReadOnlyBooleanPropertyBase.java:72)
	at javafx.base/javafx.beans.property.ReadOnlyBooleanWrapper.fireValueChangedEvent(ReadOnlyBooleanWrapper.java:103)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:111)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
	at javafx.controls/javafx.scene.control.MenuButton.setShowing(MenuButton.java:220)
	at javafx.controls/javafx.scene.control.MenuButton.show(MenuButton.java:377)
	at javafx.controls/javafx.scene.control.skin.MenuBarSkin.lambda$rebuildUI$24(MenuBarSkin.java:943)
	at javafx.scene.control.skin.MenuBarSkin$$Lambda$595/0000000000000000.changed(Unknown Source)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.base/javafx.beans.property.ReadOnlyBooleanPropertyBase.fireValueChangedEvent(ReadOnlyBooleanPropertyBase.java:72)
	at javafx.base/javafx.beans.property.ReadOnlyBooleanWrapper.fireValueChangedEvent(ReadOnlyBooleanWrapper.java:103)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:111)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
	at javafx.controls/javafx.scene.control.Menu.setShowing(Menu.java:209)
	at javafx.controls/javafx.scene.control.Menu.show(Menu.java:412)
	at javafx.controls/javafx.scene.control.skin.MenuBarSkin.showMenu(MenuBarSkin.java:470)
	at javafx.controls/javafx.scene.control.skin.MenuBarSkin.showMenu(MenuBarSkin.java:449)
	at javafx.controls/javafx.scene.control.skin.MenuBarSkin.lambda$rebuildUI$27(MenuBarSkin.java:985)
	at javafx.scene.control.skin.MenuBarSkin$$Lambda$598/0000000000000000.handle(Unknown Source)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.process(Scene.java:3856)
	at javafx.graphics/javafx.scene.Scene.processMouseEvent(Scene.java:1851)
	at javafx.graphics/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2584)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:409)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:299)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:704)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:447)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$$Lambda$1004/0000000000000000.get(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:446)
	at javafx.graphics/com.sun.glass.ui.View.handleMouseEvent(View.java:556)
	at javafx.graphics/com.sun.glass.ui.View.notifyMouse(View.java:942)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at com.sun.glass.ui.win.WinApplication$$Lambda$98/0000000000000000.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:835)
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.removeListener(ExpressionHelper.java:73)
	at javafx.base/javafx.beans.property.ReadOnlyBooleanPropertyBase.removeListener(ReadOnlyBooleanPropertyBase.java:61)
	at javafx.graphics/javafx.stage.PopupWindow.unbindOwnerFocusedProperty(PopupWindow.java:895)
	at javafx.graphics/javafx.stage.PopupWindow.doVisibleChanged(PopupWindow.java:542)
	at javafx.graphics/javafx.stage.PopupWindow$1.doVisibleChanged(PopupWindow.java:111)
	at javafx.graphics/com.sun.javafx.stage.PopupWindowHelper.visibleChangedImpl(PopupWindowHelper.java:63)
	at javafx.graphics/com.sun.javafx.stage.WindowHelper.visibleChanged(WindowHelper.java:77)
	at javafx.graphics/javafx.stage.Window$12.invalidated(Window.java:1147)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
	at javafx.graphics/javafx.stage.Window.setShowing(Window.java:1174)
	at javafx.graphics/javafx.stage.Window.hide(Window.java:1199)
	at javafx.graphics/javafx.stage.PopupWindow.hide(PopupWindow.java:486)
	at javafx.controls/javafx.scene.control.ContextMenu.hide(ContextMenu.java:295)
	at javafx.controls/javafx.scene.control.skin.MenuButtonSkinBase.hide(MenuButtonSkinBase.java:310)
	at javafx.controls/javafx.scene.control.skin.MenuButtonSkinBase.lambda$new$4(MenuButtonSkinBase.java:168)
	at javafx.scene.control.skin.MenuButtonSkinBase$$Lambda$610/0000000000000000.accept(Unknown Source)
	at javafx.controls/com.sun.javafx.scene.control.LambdaMultiplePropertyChangeListenerHandler.lambda$new$1(LambdaMultiplePropertyChangeListenerHandler.java:49)
	at javafx.controls/com.sun.javafx.scene.control.LambdaMultiplePropertyChangeListenerHandler$$Lambda$612/0000000000000000.changed(Unknown Source)
	at javafx.base/javafx.beans.value.WeakChangeListener.changed(WeakChangeListener.java:86)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:360)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.base/javafx.beans.property.ReadOnlyBooleanPropertyBase.fireValueChangedEvent(ReadOnlyBooleanPropertyBase.java:72)
	at javafx.base/javafx.beans.property.ReadOnlyBooleanWrapper.fireValueChangedEvent(ReadOnlyBooleanWrapper.java:103)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:111)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
	at javafx.controls/javafx.scene.control.MenuButton.setShowing(MenuButton.java:220)
	at javafx.controls/javafx.scene.control.MenuButton.hide(MenuButton.java:389)
	at javafx.controls/javafx.scene.control.skin.MenuBarSkin.lambda$rebuildUI$24(MenuBarSkin.java:946)
	at javafx.scene.control.skin.MenuBarSkin$$Lambda$595/0000000000000000.changed(Unknown Source)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.base/javafx.beans.property.ReadOnlyBooleanPropertyBase.fireValueChangedEvent(ReadOnlyBooleanPropertyBase.java:72)
	at javafx.base/javafx.beans.property.ReadOnlyBooleanWrapper.fireValueChangedEvent(ReadOnlyBooleanWrapper.java:103)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:111)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
	at javafx.controls/javafx.scene.control.Menu.setShowing(Menu.java:209)
	at javafx.controls/javafx.scene.control.Menu.hide(Menu.java:429)
	at javafx.controls/javafx.scene.control.skin.MenuBarSkin.unSelectMenus(MenuBarSkin.java:1068)
	at javafx.controls/javafx.scene.control.skin.MenuBarSkin.lambda$new$15(MenuBarSkin.java:396)
	at javafx.scene.control.skin.MenuBarSkin$$Lambda$602/0000000000000000.handle(Unknown Source)
	at javafx.base/javafx.event.WeakEventHandler.handle(WeakEventHandler.java:79)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler$WeakEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:282)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Scene$KeyHandler.process(Scene.java:4064)
	at javafx.graphics/javafx.scene.Scene.processKeyEvent(Scene.java:2123)
	at javafx.graphics/javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2591)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:217)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:149)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:704)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(GlassViewEventHandler.java:248)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$$Lambda$1460/0000000000000000.get(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:247)
	at javafx.graphics/com.sun.glass.ui.View.handleKeyEvent(View.java:547)
	at javafx.graphics/com.sun.glass.ui.View.notifyKey(View.java:971)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at com.sun.glass.ui.win.WinApplication$$Lambda$98/0000000000000000.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:835)
```

**Comment by dukke** [comment]
Hi Thomas (@ThomasDaheim) !

Can you add a small test sample that illustrates this bug happening? You can add it here to this issue.

And also try it with latest JavaFX version (javafx 15 or upwards). There were a bunch of bug fixes going into javafx that fixed memory leaks and wrong disposal of skins and it could be (though I don't have a test sample to test this) that this bug is related to those issues. 

Thanks! Kind regards

**Comment by ThomasDaheim** [comment]
Hi Pedro,

please find below a "minimal" example based on my use case. Tested with JavaFX 15.0.1.

Please note: the exception doesn't occur without the `hbox.setAlignment(Pos.CENTER_LEFT);`. So its probably some fringe case.

```
import java.io.File;
import javafx.application.Application;
import javafx.event.ActionEvent;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.CustomMenuItem;
import javafx.scene.control.Label;
import javafx.scene.control.Menu;
import javafx.scene.control.MenuBar;
import javafx.scene.layout.HBox;
import javafx.scene.layout.StackPane;
import javafx.stage.DirectoryChooser;
import javafx.stage.Stage;
import jfxtras.styles.jmetro.JMetro;
import jfxtras.styles.jmetro.Style;

/**
 *
 * @author thomas
 */
public class JMetroDirectoryChooserTest extends Application {
    /**
     * 
     * @param primaryStage 
     */
    @Override
    public void start(Stage primaryStage) {
        primaryStage.setTitle("DirectoryChooser with JMetro Test");

        final MenuBar menuBar = new MenuBar();
        final Menu menu = new Menu("Test");
        final CustomMenuItem menuItem = new CustomMenuItem();
        
        final HBox hbox = new HBox();
        
        // !!!no exception of not aligned in hbox!!!
        hbox.setAlignment(Pos.CENTER_LEFT);
        // !!!no exception of not aligned in hbox!!!
        
        final Label label = new Label("Path: ");
        final Label path = new Label("");
        final Button button = new Button("...");
        button.setOnAction((ActionEvent event) -> {
            // open directory chooser dialog - starting from current path, if any
            DirectoryChooser directoryChooser = new DirectoryChooser();
            directoryChooser.setTitle("Select directory");
            File selectedDirectory = directoryChooser.showDialog(primaryStage.getOwner());
            
            if(selectedDirectory != null) {
                path.setText(selectedDirectory.getPath());
            }
        });
        hbox.getChildren().addAll(label, path, button);
        
        menuItem.setContent(hbox);
        menu.getItems().add(menuItem);
        menuBar.getMenus().add(menu);
        
        final StackPane stackPane = new StackPane();
        stackPane.getChildren().add(menuBar);
        
        final Scene scene = new Scene(stackPane);
        primaryStage.setScene(scene);
        (new JMetro(Style.LIGHT)).setScene(primaryStage.getScene());
        
        primaryStage.show();
    }
}
```

**Comment by dukke** [comment]
Thanks Thomas!

**Comment by dukke** [comment]
Hi @ThomasDaheim 

I tested this with Java 11 and it works fine. 
I wonder, are you using the correct JMetro version? JMetro 8 versions are supposed to be used with Java 8. For Java11 you have to use JMetro versions starting with 11.

Thanks,

**Comment by ThomasDaheim** [comment]
I'm using 11.6.14 at the moment. It just hapened, that I forked & created the pull request without checking the version it was for...

**Comment by dukke** [comment]
OK, so I'm going to close this. Thx
