### ISSUE TITLE
Right click on button with animation causes exceptions.

### ISSUE THREAD

**Issue by MairwunNx** [JFXtras/jfxtras-styles#33]
![image](https://user-images.githubusercontent.com/39625750/51763396-915d8100-20e3-11e9-9f46-36f299880cf1.png)

###### stacktrace when right clicking on button with animation.

```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$2.handle(BehaviorSkinBase.java:107)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$2.handle(BehaviorSkinBase.java:105)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene.processMenuEvent(Scene.java:1802)
	at javafx.scene.Scene.access$4500(Scene.java:159)
	at javafx.scene.Scene$ScenePeerListener.menuEvent(Scene.java:2516)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$null$354(GlassViewEventHandler.java:466)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMenuEvent$355(GlassViewEventHandler.java:449)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMenuEvent(GlassViewEventHandler.java:448)
	at com.sun.glass.ui.View.handleMenuEvent(View.java:563)
	at com.sun.glass.ui.View.notifyMenu(View.java:889)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by MairwunNx** [comment]
@dukke no problem! :)

**Comment by dukke** [comment]
@MairwunNx This doesn't seem to happen to me right now. Perhaps this was from an older Java version? Or perhaps was happening on an older JMetro version?
