### ISSUE TITLE
DatePicker: open calendar twice causes exception

### ISSUE THREAD

**Issue by maokejackson** [JFXtras/jfxtras-styles#97]
The exception can be reproduced with follow code snippet:

```
Scene scene = new Scene(new DatePicker());

new JMetro(JMetro.Style.LIGHT).applyTheme(scene);

primaryStage.setScene(scene);
primaryStage.show();
```

Steps to reproduce:

1. Click the calendar button, the calendar prompts.
2. Click the calendar button, the calendar hides.
3. Click the calendar button, the calendar prompts with exception prints in console.

```
Exception in thread "JavaFX Application Thread" java.lang.ClassCastException: com.sun.javafx.scene.control.skin.ButtonSkin cannot be cast to impl.jfxtras.styles.jmetro8.FluentButtonSkin
	at impl.jfxtras.styles.jmetro8.FluentButtonSkin$1.getStyleableProperty(FluentButtonSkin.java:39)
	at impl.jfxtras.styles.jmetro8.FluentButtonSkin$1.getStyleableProperty(FluentButtonSkin.java:29)
	at javafx.scene.CssStyleHelper.resetToInitialValues(CssStyleHelper.java:447)
	at javafx.scene.CssStyleHelper.createStyleHelper(CssStyleHelper.java:180)
	at javafx.scene.Node.reapplyCss(Node.java:8983)
```

I am using Oracle JDK 1.8 with JMetro 5.6.

**Comment by dukke** [comment]
Just finishing up a release that will come next week. I'll look at this issue right afterwards.

**Comment by dukke** [comment]
Fixed in 8..7.8.
Thanks!

**Comment by dukke** [comment]
8.5.8 actually.
